### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by FelixGail** [kontrollanten/couchdb-hastings-docker#1]
Hey,
i would like to alter and use this Docker. If this is alright with you, could you add a bsd/mit licence?

This would be a great help.

Best regards,
Felix

**Comment by kontrollanten** [comment]
Hi Felix! Of course!

What are your plans? You're welcome to do a PR if you have any improvements.

Edit: The license is added, enjoy!

**Comment by FelixGail** [comment]
i am planning to use this together with openwhisk. my changes will therefore probably not improve, but alter the configuration for my purpuse. 

big thanks :)
